services:
  web:
    image: flask_counter
    build: .
    ports:
      - "80:5000"
    depends_on:
      - redis
    volumes:
      - type: bind
        source: /home/gaizka/Documents/GitHub/sysadmin-labo/L6/
        target: /code/
    environment:
      - FLASK_DEBUG=1
    restart: on-failure

  redis:
    image: redis:alpine
